"""add patients

Revision ID: 93d351063ade
Revises: 29eea41b0e36
Create Date: 2026-06-03 19:14:39.987260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d351063ade'
down_revision: Union[str, None] = '29eea41b0e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('chief_complaint', sa.String(), nullable=False),
    sa.Column('symptom_duration', sa.String(), nullable=False),
    sa.Column('mood_rating', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('current_medications', sa.String(), nullable=True),
    sa.Column('past_psychiatric_history', sa.String(), nullable=True),
    sa.Column('family_psychiatric_history', sa.String(), nullable=True),
    sa.Column('substance_use', sa.String(), nullable=True),
    sa.Column('suicidal_ideation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_patients_provider_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patients')
    # ### end Alembic commands ###
